import { Article } from "@/types/Article";

export const headlines: Article[] = [
  {
    image: "/images/post-1.png",
    title: "Global Climate Summit Addresses Urgent Climate Action",
    description:
      "World leaders gathered at the Global Climate Summit to discuss urgent climate action, emissions reductions.",
    category: "Environment",
    date: "October 10, 2023",
    author: "Jane Smith",
    likes: "14K",
    shares: "204",
    slug: "global-climate-summit-addresses-urgent-climate-action",
    isFeatured: true,
    index: 0,
  },
  {
    image: "/images/post-2.png",
    title: "A Decisive Victory for Progressive Policies",
    description: "na",
    category: "Politics",
    date: "na",
    author: "na",
    likes: "2.2K",
    shares: "60",
    slug: "a-decisive-victory-for-progressive-policies",
    isFeatured: false,
    index: 1,
  },
  {
    image: "/images/post-3.png",
    title: "Tech Giants Unveil Cutting-Edge AI Innovations",
    description: "na",
    category: "Technology",
    date: "na",
    author: "na",
    likes: "6K",
    shares: "92",
    slug: "tech-giants-unveil-cutting-edge-ai-innovations",
    isFeatured: false,
    index: 2,
  },
  {
    image: "/images/post-4.png",
    title: "COVID-19 Variants",
    description: "na",
    category: "Health",
    date: "na",
    author: "na",
    likes: "10K",
    shares: "124",
    slug: "covid-19-variants",
    isFeatured: false,
    index: 3,
  },
];
