import "@/styles/globals.css";
import "@/components/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/Header";

const inter = localFont({
  src: "../../public/fonts/Inter-VariableFont_opsz,wght.ttf",
  style: "normal",
  variable: "--font-inter",
  display: "swap",
});

const kumbhSans = localFont({
  src: "../../public/fonts/KumbhSans-VariableFont_YOPQ,wght.ttf",
  style: "normal",
  variable: "--font-kumbh",
  display: "swap",
});

export const metadata: Metadata = {
  title: "FutureTech Blog",
  description: "Generated by create next app",
  robots: {
    index: process.env.NODE_ENV === "production",
    follow: process.env.NODE_ENV === "production",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${kumbhSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
